export * from './login/LoginPage';
export * from './Home/HomePage';
export * from './Equipos';
export * from './Usuarios';
export * from './FormRoles';
export * from './FormPropietarios';
export * from './FormMantenimientos'
export * from './Equipos/ListaEquipos'
export * from './Usuarios/ListaUsuarios'
