export * from './login/LoginPage';
export * from './Home/HomePage';
export * from './Equipos';
export * from './Usuarios';
export * from './FormRoles';
export * from './FormCuentadantes';
export * from './FormMantenimientos'
export * from './Equipos/ListaEquipos'
export * from './Usuarios/ListaUsuarios'
export * from './FormMantenimientos/GestionMantenimiento'
export * from './Areas'
export * from './Tipos'
